name: "[macos] Build and test"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    name: build and test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install libgit2 json-c uthash iniparser
        brew install bash bats-core

    - name: Build binary
      run: make build
    
    - name: Run tests
      run: |
        # meta about environment
        bash --version
        echo $-
        bats --version

        # run test
        make test
