name: "[macos] Build, test, upload"

on:
  pull_request:
    types: [opened, reopened, synchronize]

  push:
    branches:
      - '*'
  
jobs:
  build-test-upload:
    name: build, test, upload
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install libgit2 json-c uthash iniparser
        brew install bash bats-core

    - name: Build binary
      run: make build
    
    - name: Run tests
      run: |
        # meta about environment
        bash --version
        echo $-
        bats --version

        # run test
        make test
 
    - name: Upload binaries as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: 'prompt2-bundle-macos-latest'
        path: |
          bin/prompt2
          bin/get-attribute
  
  
  