name: "[ubuntu] Build and test"

on:
  pull_request:
    types: [opened, reopened, synchronize]

  push:
    branches:
      - '*'
      
jobs:
  build-and-test:
    name: build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get install libgit2-dev libjson-c-dev uthash-dev libiniparser-dev

        curl -Lo bats-core.tar.gz https://github.com/bats-core/bats-core/archive/v1.10.0.tar.gz
        tar -xzf bats-core.tar.gz
        cd bats-core-1.10.0
        sudo ./install.sh /usr/local

    - name: Build binary
      run: make build

    - name: Run tests
      run: |
        # meta about environment
        bash --version
        echo $-
        bats --version
        
        # run test
        make test
